apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: monitoring-logstash
spec:
  serviceName: "logstash"
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-logstash
  template:
    metadata:
      labels:
        app: monitoring-logstash
    spec:
      containers:
        - name: nginx
          image: ubuntu:22.04
          command: ["sleep","3600"]
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "15Mi"
              cpu: "15m"
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi